version: "3.9"
services:
  monitoring:
    image: "samply/bridgehead-monitoring:main"
    container_name: bridgehead-monitoring
    environment: 
      HOST: ${HOST}
      SITE_NAME: ${SITE_NAME}
      PROJECT: ${PROJECT}
      BEAM_URL: ${BEAM_URL}
      PROXY_ID: ${PROXY_ID}
      MONITORING_TARGET: ${MONITORING_TARGET}
      KEY: ${KEY}
    